version = 1

[[analyzers]]
name = "secrets"
enabled = true

[[analyzers]]
name = "shell"
enabled = true

[[analyzers]]
name = "docker"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

    [analyzers.meta]
    environment = ["nodejs"]

[[transformers]]
name = "prettier"
enabled = true